language: julia
os:
    - linux
julia:
    - 1
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
script:
- julia -e 'const PACKAGE = ENV["PACKAGE"]; using Pkg; Pkg.develop("MathOptInterface"); Pkg.develop(PACKAGE); Pkg.test(PACKAGE)'
jobs:
  include:
    - env: PACKAGE=Alpine
    - env: PACKAGE=Tulip
